// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiredBrainCoffee.EmployeeManager.Contexts;

#nullable disable

namespace WiredBrainCoffee.EmployeeManager.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20230209212930_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            FirstName = "Anna",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 5,
                            FirstName = "Julia",
                            IsDeveloper = true,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 4,
                            FirstName = "Lily",
                            IsDeveloper = false,
                            LastName = "Valley"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 5,
                            FirstName = "Corky",
                            IsDeveloper = true,
                            LastName = "Delve"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FirstName = "Jeff",
                            IsDeveloper = false,
                            LastName = "Britian"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 5,
                            FirstName = "Andrew",
                            IsDeveloper = true,
                            LastName = "McCoy"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            FirstName = "Salesboat",
                            IsDeveloper = false,
                            LastName = "F."
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            FirstName = "Walt",
                            IsDeveloper = false,
                            LastName = "Mink"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            FirstName = "Showboat",
                            IsDeveloper = false,
                            LastName = "Wells"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 4,
                            FirstName = "Stephanie",
                            IsDeveloper = false,
                            LastName = "Shucks"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 5,
                            FirstName = "Betty",
                            IsDeveloper = true,
                            LastName = "Ford"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            FirstName = "Kitchen",
                            IsDeveloper = false,
                            LastName = "Half"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 5,
                            FirstName = "Bev",
                            IsDeveloper = true,
                            LastName = "Bevins"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            FirstName = "Anderson",
                            IsDeveloper = false,
                            LastName = "McMurray"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 2,
                            FirstName = "X.",
                            IsDeveloper = false,
                            LastName = "Spot"
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Entities.Employee", b =>
                {
                    b.HasOne("WiredBrainCoffee.EmployeeManager.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
